// auto-generated by json-schema-preprocessor. DO NOT MODIFY BY HAND.

import * as t from "io-ts";

import { SchemaA } from "../schemaA/SchemaA";
export interface Schema2 {
  test: string;
  schema1: SchemaA;
}

import { tSchemaA } from "../schemaA/SchemaA";

export const tSchema2 = t.interface({
  test: t.string,
  schema1: tSchemaA,
});
