// auto-generated by json-schema-preprocessor. DO NOT MODIFY BY HAND.

import * as t from "io-ts";

export interface SchemaA {
  context: string;
  message: string;
  code: string;
  count?: number;
  count2?: number;
  nullable?: null;
  list?: Array<{
    nested?: string,
  }>;
}

export const tSchemaA = t.intersection([
  t.interface({
    context: t.string,
    message: t.string,
    code: t.string,
  }),
  t.partial({
    count: t.number,
    count2: t.number,
    nullable: t.null,
    list: t.array(
      t.partial({
        nested: t.string,
      }),
    ),
  }),
]);
