// auto-generated by json-schema-preprocessor. DO NOT MODIFY BY HAND.

import * as t from "io-ts";

export interface Person {
  firstName?: string;
  lastName?: string;
  age?: number;
}

export const tPerson = t.partial({
  firstName: t.string,
  lastName: t.string,
  age: t.number,
});
