// auto-generated by json-schema-preprocessor. DO NOT MODIFY BY HAND.

import * as t from "io-ts";

export interface Geo {
  latitude: number;
  longitude: number;
}

export const tGeo = t.interface({
  latitude: t.number,
  longitude: t.number,
});
